# Generated by Django 3.2 on 2021-05-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ismi')),
                ('email', models.EmailField(max_length=200, verbose_name='Emaili')),
                ('subject', models.CharField(max_length=50, verbose_name='subject')),
                ('message', models.CharField(max_length=250, verbose_name='Xabari')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'Contactlar',
            },
        ),
    ]
